### ISSUE TITLE
Popup doesn't offer "dismiss" option and can't be terminated

### ISSUE THREAD

**Issue by JESii** [Clemens-E/obsidian-languagetool-plugin#107]
<img width="376" alt="CleanShot 2023-10-06 at 08 12 46@2x" src="https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/486/5c8bef3f-4414-4714-a3f8-0a04ec798ed5">

All I can do is accept the suggestion or add it to my personal dictionary -- where's the "ignore suggestion" option?

And how do I kill the popup entirely -- there's no "x" and {Esc} doesn't work.

**Comment by brandones** [comment]
You can click anywhere outside the popup to close it.

**Comment by 0atman** [comment]
@JESii or use the cursor keys (or vim keys, like I use) to move outside of the word.
OR:
@Clemens-E did a great job making this plugin keyboard-friendly, but you have to map them yourself (like most obsidian themes): My workflow is to map the keyboard shortcuts for "Accept suggestion #1" to Ctrl+1 (and 2, 3, 4, 5)

That way I can dismiss and accept suggestions all with the keyboard - LOVELY!

**Comment by JESii** [comment]
Thanks for the info @0atman - very helpful!

**Comment by blay** [comment]
This issue was closed, but it would be a great feature to be able to close the popup while still having the cursor on the underlined word. In the above example, the user neither wants to add to the personal dictionary nor want to correct the word, so will have the popup constantly show up when the cursor is on this word unless they clear all suggestions from the file.
