### ISSUE TITLE
Request to LanguageTool failed

### ISSUE THREAD

**Issue by NB574** [Clemens-E/obsidian-languagetool-plugin#15]
Hi I've been getting the below today, is this plugin related or related to the LanguageTool api?

![image](https://user-images.githubusercontent.com/80176672/119271930-11d51380-bc04-11eb-90a3-0c5ffaa546f6.png)

**Comment by Clemens-E** [comment]
Hi, this could either be because the LangaugeTool API is not working correctly, or because the plugin did something wrong.
Does this happen all the time or with specific settings?
it may be
- your note is too big (maximum of 20,000 Characters)
- you sent too many requests
- the plugin did something wrong

it would help if you did the following:
1. Open the Debug Tools by pressing "Shift + Ctrl + i"
2. Switch to the "Network" tab
3. run the plugin so it produces this error, preferable on a note that you dont care about publishing the content
4. click on the newest request with "check" in the name, and show a few screenshots of the "headers" tab and "preview".

https://user-images.githubusercontent.com/43886026/119272714-9b3a1500-bc07-11eb-9301-5b339e78c74e.mp4

**Comment by NB574** [comment]
Thanks for the quick response. My notes tend to be about 1000-2000 char max, and my vault's not particularly big, so I doubt it's that. I've never had a problem with it before today, it's always worked great. Considering there's a 404 showing for the api, I'm gussing the issue is there, rather than the plugin itself? I've also tested it on a blank vault, with no notes, snippets or other plugins, and get the same response. 

Can I just say I love your plugin by the way. I'm English but do most of my writing in Danish, and finally having some way of being able to spellcheck Danish direct in Obsidian is an absolute godsend. Tyvm.

![image](https://user-images.githubusercontent.com/80176672/119273392-0d602900-bc0b-11eb-906f-9ba42cf92af3.png)
![image](https://user-images.githubusercontent.com/80176672/119273398-181abe00-bc0b-11eb-820f-0180f69eef95.png)

**Comment by Clemens-E** [comment]
Oh, yes, I see why that happened. The Plugin didn't migrate the settings (@mgmeyers 👀)
You can go to the plugins settings and reset the endpoint config, or simply uninstall and install the plugin.

I will release a version that fixes this.

**Comment by NB574** [comment]
Oh I wasn't sure if I'd screw something up by pressing the reset button. Just done it now and it works again, thank you!
