### ISSUE TITLE
Suggestions don't disappear

### ISSUE THREAD

**Issue by phlind** [Clemens-E/obsidian-languagetool-plugin#2]
Thanks for making the plugin! As of now, sometimes the suggestions do not disappear at all, sometimes they disappear after some seconds. Would it be possible to make them disappear by clicking somewhere else in the text? Also, they stay present when switching to another file.

**Comment by Clemens-E** [comment]
Hi, this is currently solved very clunky, the suggestions disappears one second after the "mouseleave" event.
So, if you hover over them and then move your mouse away, they should disappear.
I had some problems with the "clicking somewhere else" thing, and didn't want to spend too much time on it because I just wanted to get a test version out there.
I will probably fix this today or tomorrow, thank you for testing!

**Comment by phlind** [comment]
Ok, I see. It does indeed always disappear, but only after hovering over the popup. So when you go upwards from the word and don't hit the popup, it stays.

**Comment by Clemens-E** [comment]
fixed, they should now disappear when clicking anywhere in the editor
