### ISSUE TITLE
Wrong Recommendation(s)

### ISSUE THREAD

**Issue by notthelewis** [Clemens-E/obsidian-languagetool-plugin#30]
Hey, 

First up, very nice tool- I've only been using it a few hours but it's great so far... Nice work!
I know that this extends languagetool, so this may well be an issue for them, but I thought it right to report it here too. 

It's happened a few times so far but most of them I'll just click 'ignore suggestion' and not pay any mind. But this particular instance seemed like a pretty grievous grammar mistake.

![image](https://user-images.githubusercontent.com/43108320/127873391-2459a9df-8f56-4e9d-944f-12ab66a4e185.png)

Before I go ahead and report this to LanguageTool, I was wondering whether this was an issue your side or theirs. 

Thanks in advance!

**Comment by notthelewis** [comment]
Just to add to this, I also get this weird bug when using bold text, shown here:

![image](https://user-images.githubusercontent.com/43108320/127874036-dac278b7-5695-4055-9912-5e03bd04d59f.png)

**Comment by Clemens-E** [comment]
Hi, 
it seems like the first case happens because of the rule 
[Plain English "obtain (get)"](https://community.languagetool.org/rule/show/OBTAIN?lang=en&subId=1)
This rule is disabled in the original LanguageTool, but we set it. You can temporarily fix this issue by disabling the "Plain English" Rule in the LT Settings Tab. (Please restart Obsidian after doing that)

About the second issue: I don't know, and I can't replicate it. Is this the only content of that note? Maybe LT detects a wrong langauge.

@mgmeyers maybe we shouldn't enable every rule? LanguageTool probably has those disabled for a reason.

**Comment by notthelewis** [comment]
Thank you for getting back to me so quickly. Disabling `Plain English` and restarting Obsidian unfortunately did not make any difference.

I didn't even know there was a tab for plugin settings before now (new Obsidian user), so thanks for bringing that to my attention. I did find that setting the static language to my system default (English GB) completely resolved the secondary issue. 

Weirdly enough, if I use the keyboard shortcut for bold text (ctrl+b) and type Pass The Hash (without static language enabled), it throws that weird suggestion but if I manually type `**` before and after, it doesn't throw it... strange. Anyways, static language fixed that one and I can cope with the weird suggestions for the time being.

**Comment by Clemens-E** [comment]
Hm, weird, disabling "Plain English" fixed it for me

**Comment by Clemens-E** [comment]
Hi @notthelewis, in the new update I have completely removed the rule toggles, do you still have this behavior?

**Comment by notthelewis** [comment]
Just tried it now and the problem appears to be resolved. Nice work!
