### ISSUE TITLE
Personal Dictionary

### ISSUE THREAD

**Issue by Preluck07** [Clemens-E/obsidian-languagetool-plugin#41]
Is there a way to access the Personal Dictionary, I tried looking for it and didn't find it

**Comment by mgmeyers** [comment]
@Preluck07 This plugin uses obsidian's spellcheck dictionary. To access that, you have to enable spellcheck and click on this icon:

<img width="1008" alt="Screen Shot 2021-11-27 at 11 53 41 AM" src="https://user-images.githubusercontent.com/2694747/143720500-56d1e3c4-b486-41f4-a58e-99c13b6debf3.png">

**Comment by paulkre** [comment]
Are you sure this is the case? I added words to my personal dictionary but Obsidian's spellcheck dictionary is still empty.

**Comment by arlenxuzj** [comment]
> Are you sure this is the case? I added words to my personal dictionary but Obsidian's spellcheck dictionary is still empty.

@paulkre  You can find it in `obsidian/app.json`.

**Comment by Ellpeck** [comment]
It seems that, since this issue was closed, Obsidian's built-in spellcheck dictionary has moved to a location outside the vault (perhaps the local app data, where Obsidian stores a multitude of other information specific to the machine it's running on).

When this plugin adds entries to its spellcheck dictionary, they are added to the `app.json`, but do not show up in the spellcheck dictionary option in Obsidian. Conversely, when adding entries to Obsidian's spellcheck dictionary, they are not added to the `app.json`.

I think it would be nice to be able to view this plugin's spell check dictionary specifically, or be able to toggle an option to save this plugin's spellcheck dictionary to Obsidian's new location.

**Comment by tonymynd** [comment]
> > Are you sure this is the case? I added words to my personal dictionary but Obsidian's spellcheck dictionary is still empty.
> 
> @paulkre You can find it in `obsidian/app.json`.

![image](https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/84558942/b832e215-5cb9-4fbe-9249-ba4bc4983061)
