### ISSUE TITLE
LanguageTool Premium fails (v2 APIs?)

### ISSUE THREAD

**Issue by simsalis** [Clemens-E/obsidian-languagetool-plugin#63]
The request using the API key fails when selecting “Premium” endpoint—endless check, no results, all values verified multiple times.

So, I noticed the suggested Endpoint is now https://api.languagetoolplus.com/v2 from the LT account dashboard, and I set that up in the Options for the Obsidian plugin by choosing “Custom.”

This also fails, with a different error. Wondering if there are any updates needed for the Premium part to work with v2 APIs and certain recently issued keys?

![image](https://user-images.githubusercontent.com/26729065/181794359-25fe1d94-0971-4270-9b8c-d4dc23a6e3cd.png)

**Comment by Clemens-E** [comment]
The v2 API is not new and used since forever, so changing the url to "https://api.languagetoolplus.com/v2" only made the plugin call "https://api.languagetoolplus.com/v2/v2" which then causes that notification.


To further look into this, I would need to look at any errors appearing, as everything works fine for me.
Please follow the steps described in this comment https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/15#issuecomment-846607182
**censor your email and apiKey if they are visible**

**Comment by gernotstarke** [comment]
@simsalis I installed the plugin a few days ago, and (successfully) use this URL for premium access within Obsidian:

`https://api.languagetoolplus.com`

The API access needs to be enabled (manually) by the LanguageTool support team - it took about one hour after I requested the access (via email). 

After doing that, everything worked fine...

**Comment by simsalis** [comment]
Removing plus addressing from the email resolved the problem.

Everything was already configured correctly otherwise.
