### ISSUE TITLE
Setting static language cause error

### ISSUE THREAD

**Issue by yifanyin** [Clemens-E/obsidian-languagetool-plugin#79]
The plugin will fail with message "Request to LanguageTool failed" if a static language is set instead of "auto detect".

**Comment by Clemens-E** [comment]
Yeah... what do you want the plugin to do about that? Just don't set both of those things

**Comment by Clemens-E** [comment]
You can't set a static language *and* "Interpret XYZ as". You have to remove one of those.

**Comment by RoboDave21** [comment]
For me it even says "Request to LanguageTool failed" with Auto Detect on. I stopped working a couple days ago. I tried reinstalling it but still doesn't work.
Obsidian v1.0.3

**Comment by RoboDave21** [comment]
I updated and it worked. But today I started writing again and after about half an hour I get the "Request to LanguageTool failed" again. Then I read the failed request logs and it just doesn't work because I have more than 20000 characters in the document. So I guess I need to get the premium version for this to work.

 27.11.2022, 14:31:53:
  url used for request: https://api.languagetool.org/v2/check
  Status: 413
  Body: Error: Your text exceeds the limit of 20000 characters (it's 20776 characters). Please submit a shorter text.
  Settings: {"serverUrl":"https://api.languagetool.org","urlMode":"standard","glassBg":false,"shouldAutoCheck":true,"pickyMode":false,"staticLanguage":"auto","englishVeriety":"en-US","germanVeriety":"de-DE","username":"REDACTED","apikey":"REDACTED"}

**Comment by Clemens-E** [comment]
I don't know if Premium increases the limit, you can select a portion of the text and then run the check again, it will only check the text you selected.
