### ISSUE TITLE
went premium now can't connect 

### ISSUE THREAD

**Issue by rolodexter** [Clemens-E/obsidian-languagetool-plugin#86]
![image](https://user-images.githubusercontent.com/977925/208556671-50c2d4f4-8d4a-4881-b096-7f7f18b8c1df.png)

went premium haven't been able to connect since

**Comment by Clemens-E** [comment]
Very verbose report...
Can you go into the settings of the LanguageTool Integration and click on "copy failed requests log", and if you can't make any sense of it, paste it here?

**Comment by hverlin** [comment]
In case this helps, I had to manually enter `https://api.languagetoolplus.com` in the text input here otherwise I would get a similar error. 

The request logs were empty.

![image](https://user-images.githubusercontent.com/9151470/210059891-3243a12c-b1f5-4dac-8dc9-d8af533f5a45.png)

What's a bit confusing is that on the [languagetool website](https://languagetool.org/editor/settings/access-tokens), they suggest another endpoint 
![image](https://user-images.githubusercontent.com/9151470/210059978-d877c911-67a9-4a36-8aae-148ec9e6cc20.png)

If one uses it, then you get a 404, as the plugin is automatically adding `/v2` at the end of the URL
```
  url used for request: https://api.languagetoolplus.com/v2/v2/check
  Status: 404
```

**Comment by Clemens-E** [comment]
Yeah the link on the LanguageTool website is wrong. You can just select the "Premium" one in the drop-down and it just works without manually entering any URL.


If not, please create a new but with steps to reproduce the bug.

Closing this as author is not responding
