### ISSUE TITLE
[Bug] Some correctly spelled words keep being flagged

### ISSUE THREAD

**Issue by hemicyon** [Clemens-E/obsidian-languagetool-plugin#87]
Language is manually set to English GB, and I’ve disabled rule EN_WORD_COHERENCY, but certain words are still being flagged for review. E.g. organise/organisation, realise/realisation continue to get flagged with an **Oxford spelling: -ise verbs/nouns** message prompting a choice between changing the word to *ize* (despite acknowledging that both are correct) or ignore the suggestion. Other words with more than one correct spelling—such as behaviour, colour, aeroplane, neighbour, licence, archaeology—are not being flagged for review. I couldn’t manage to find any other rule that might be the cause, which is why I’m thinking this is probably a bug.

**Comment by Clemens-E** [comment]
I don't know what exactly your issue is, but if you have issues with the resulting checks, you should repeat on https://languagetool.org/editor/. This way you know if it's an issue with the plugin or an issue with how LanguageTool rules (which you wouldn't report on this plugin)

I tried this, please let me know if that's what you meant:
![grafik](https://user-images.githubusercontent.com/43886026/209134372-36c07d16-b678-4990-ae14-4c379df2b31e.png)
And you expected this to not show? My knowledge on GB/US differences is not big enough, so no clue if that's correct, but you can disable the rule `OXFORD_SPELLING_Z_NOT_S` to ignore this (make sure to restart obsidian or edit the note before checking again)

Read the rule definition here:
https://community.languagetool.org/rule/show/OXFORD_SPELLING_Z_NOT_S?lang=en-GB&subId=2

**Comment by hemicyon** [comment]
I see, thanks! That’s the message I was talking about, yes. And no, I would definitely not expect to see this correction for British English (I’ve been assuming GB indicates Great Britain…realising now that I may be wrong about that though?). 

Also just to note, I did search the rule list for the terms *Oxford* and *spelling*, and the rule *Oxford_Spelling_Z_not_S* was never in the results. I just double checked both search terms again right now to make sure I hadn’t missed it, but it still isn’t showing up in any search results.
![IMG_0616](https://user-images.githubusercontent.com/75453443/209194010-02d0c167-2d99-4b93-bc61-2896727a0424.jpeg)
![IMG_0617](https://user-images.githubusercontent.com/75453443/209194092-905d7ab2-51db-40a6-8754-b66b0fb3b486.jpeg)


Either way, I’ve disabled it now, and that has solved the issue. Wouldn’t’ve found that rule without your help. Cheers!

**Comment by vanbang9710** [comment]
same I wonder why I can only find this rule through google
